// <auto-generated>
// This file was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

internal static class SandboxToolsInteropModelDocInternal
{
	public static int Convert( Type t )
	{
		if ( typeof( global::Editor.BaseScrollWidget ).IsAssignableFrom( t ) ) return 256245278;
		if ( typeof( global::Editor.Button ).IsAssignableFrom( t ) ) return 2120449044;
		if ( typeof( global::Editor.Checkbox ).IsAssignableFrom( t ) ) return 772888385;
		if ( typeof( global::Editor.ComboBox ).IsAssignableFrom( t ) ) return 256233403;
		if ( typeof( global::Editor.Frame ).IsAssignableFrom( t ) ) return 416267623;
		if ( typeof( global::Editor.GraphicsView ).IsAssignableFrom( t ) ) return 774054386;
		if ( typeof( global::Editor.Label ).IsAssignableFrom( t ) ) return -1333028724;
		if ( typeof( global::Editor.LineEdit ).IsAssignableFrom( t ) ) return -2137430376;
		if ( typeof( global::Editor.MenuBar ).IsAssignableFrom( t ) ) return -1325607872;
		if ( typeof( global::Editor.StatusBar ).IsAssignableFrom( t ) ) return -1890426169;
		if ( typeof( global::Editor.TextEdit ).IsAssignableFrom( t ) ) return 1008106499;
		if ( typeof( global::Editor.ToolBar ).IsAssignableFrom( t ) ) return -2124457813;
		if ( typeof( global::Editor.Window ).IsAssignableFrom( t ) ) return -1571505210;
		if ( typeof( global::Editor.DockManager ).IsAssignableFrom( t ) ) return -2135796158;
		if ( typeof( global::Editor.GraphicsItem ).IsAssignableFrom( t ) ) return 2109064242;
		if ( typeof( global::Editor.GraphicsScene ).IsAssignableFrom( t ) ) return -735098127;
		if ( typeof( global::Editor.GraphicsWidget ).IsAssignableFrom( t ) ) return -120989933;
		if ( typeof( global::Editor.Option ).IsAssignableFrom( t ) ) return 780535505;
		if ( typeof( global::Editor.TrayIcon ).IsAssignableFrom( t ) ) return 1020660495;
		if ( typeof( global::Editor.Widget ).IsAssignableFrom( t ) ) return 323741830;
		
		throw new System.Exception( $"Can't handle type {t}" );
	}
}
internal unsafe readonly partial struct CModelDoc
{
	internal readonly IntPtr self;
	
	// Allow blindly converting from an IntPtr
	static public implicit operator IntPtr( CModelDoc value ) => value.self;
	static public implicit operator CModelDoc( IntPtr value ) => new CModelDoc( value );
	
	// Allow us to compare these pointers
	public static bool operator ==( CModelDoc c1, CModelDoc c2 ) => c1.self == c2.self;
	public static bool operator !=( CModelDoc c1, CModelDoc c2 ) => c1.self != c2.self;
	public readonly override bool Equals( object obj ) => obj is CModelDoc c && c == this;
	
	internal CModelDoc( IntPtr ptr ) { self = ptr; }
	public override string ToString() => $"CModelDoc {self:x}";
	// Helpers to check validity
	
	internal readonly bool IsNull{ [MethodImpl( MethodImplOptions.AggressiveInlining )] get { return self == IntPtr.Zero; } }
	internal readonly bool IsValid => !IsNull;
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly IntPtr GetPointerAssertIfNull(){ if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelDoc was null" ); return self; }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	public readonly override int GetHashCode() => self.GetHashCode();
	
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void DeleteThis() { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelDoc was null when calling DeleteThis" );__N.CModelDoc_DeleteThis( self ); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal static global::CModelDoc Create() { if ( __N.CModelDoc_Create == null ) throw new System.Exception( "Function Pointer Is Null" );return __N.CModelDoc_Create(); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly bool SaveToFile( string pFullPath ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelDoc was null when calling SaveToFile" );var _str_pFullPath = new Sandbox.Interop.InteropString( pFullPath ); try { return __N.CModelDoc_SaveToFile( self, _str_pFullPath.Pointer ) != 0; } finally { _str_pFullPath.Free(); }  }
	internal static class __N
	{
		internal static delegate* unmanaged< IntPtr, void > CModelDoc_DeleteThis;
		internal static delegate* unmanaged< IntPtr > CModelDoc_Create;
		internal static delegate* unmanaged< IntPtr, IntPtr, int > CModelDoc_SaveToFile;
	}
}

namespace NativeModelDoc
{
	internal unsafe readonly partial struct CModelDocEditorApp
	{
		internal readonly IntPtr self;
		
		// Allow blindly converting from an IntPtr
		static public implicit operator IntPtr( CModelDocEditorApp value ) => value.self;
		static public implicit operator CModelDocEditorApp( IntPtr value ) => new CModelDocEditorApp( value );
		
		// Allow us to compare these pointers
		public static bool operator ==( CModelDocEditorApp c1, CModelDocEditorApp c2 ) => c1.self == c2.self;
		public static bool operator !=( CModelDocEditorApp c1, CModelDocEditorApp c2 ) => c1.self != c2.self;
		public readonly override bool Equals( object obj ) => obj is CModelDocEditorApp c && c == this;
		
		internal CModelDocEditorApp( IntPtr ptr ) { self = ptr; }
		public override string ToString() => $"CModelDocEditorApp {self:x}";
		// Helpers to check validity
		
		internal readonly bool IsNull{ [MethodImpl( MethodImplOptions.AggressiveInlining )] get { return self == IntPtr.Zero; } }
		internal readonly bool IsValid => !IsNull;
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal readonly IntPtr GetPointerAssertIfNull(){ if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelDocEditorApp was null" ); return self; }
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		public readonly override int GetHashCode() => self.GetHashCode();
		
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal readonly void RefreshGameData() { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelDocEditorApp was null when calling RefreshGameData" );__N.CMdlDcdtrpp_RefreshGameData( self ); }
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal readonly string GetSessionModel() { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelDocEditorApp was null when calling GetSessionModel" );return Sandbox.Interop.GetString( __N.CMdlDcdtrpp_GetSessionModel( self ) ); }
		internal static class __N
		{
			internal static delegate* unmanaged< IntPtr, void > CMdlDcdtrpp_RefreshGameData;
			internal static delegate* unmanaged< IntPtr, IntPtr > CMdlDcdtrpp_GetSessionModel;
		}
	}
}

internal unsafe readonly partial struct CModelMesh
{
	internal readonly IntPtr self;
	
	// Allow blindly converting from an IntPtr
	static public implicit operator IntPtr( CModelMesh value ) => value.self;
	static public implicit operator CModelMesh( IntPtr value ) => new CModelMesh( value );
	
	// Allow us to compare these pointers
	public static bool operator ==( CModelMesh c1, CModelMesh c2 ) => c1.self == c2.self;
	public static bool operator !=( CModelMesh c1, CModelMesh c2 ) => c1.self != c2.self;
	public readonly override bool Equals( object obj ) => obj is CModelMesh c && c == this;
	
	internal CModelMesh( IntPtr ptr ) { self = ptr; }
	public override string ToString() => $"CModelMesh {self:x}";
	// Helpers to check validity
	
	internal readonly bool IsNull{ [MethodImpl( MethodImplOptions.AggressiveInlining )] get { return self == IntPtr.Zero; } }
	internal readonly bool IsValid => !IsNull;
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly IntPtr GetPointerAssertIfNull(){ if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null" ); return self; }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	public readonly override int GetHashCode() => self.GetHashCode();
	
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void DeleteThis() { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null when calling DeleteThis" );__N.CModelMesh_DeleteThis( self ); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal static global::CModelMesh Create() { if ( __N.CModelMesh_Create == null ) throw new System.Exception( "Function Pointer Is Null" );return __N.CModelMesh_Create(); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void AddVertices( int nNumVertices ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null when calling AddVertices" );__N.CModelMesh_AddVertices( self, nNumVertices ); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void AddFaceGroup( string pMaterialName ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null when calling AddFaceGroup" );var _str_pMaterialName = new Sandbox.Interop.InteropString( pMaterialName ); try { __N.CModelMesh_AddFaceGroup( self, _str_pMaterialName.Pointer ); } finally { _str_pMaterialName.Free(); }  }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void SetPositions( IntPtr pPositions, int nNumPositions ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null when calling SetPositions" );__N.CModelMesh_SetPositions( self, pPositions, nNumPositions ); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void SetTexCoords( IntPtr pTexCoords, int nNumTexCoords ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null when calling SetTexCoords" );__N.CModelMesh_SetTexCoords( self, pTexCoords, nNumTexCoords ); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void SetNormals( IntPtr pNormals, int nNumNormals ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null when calling SetNormals" );__N.CModelMesh_SetNormals( self, pNormals, nNumNormals ); }
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal readonly void AddFace( int nGroupIndex, IntPtr pVertices, int nNumVertices ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CModelMesh was null when calling AddFace" );__N.CModelMesh_AddFace( self, nGroupIndex, pVertices, nNumVertices ); }
	internal static class __N
	{
		internal static delegate* unmanaged< IntPtr, void > CModelMesh_DeleteThis;
		internal static delegate* unmanaged< IntPtr > CModelMesh_Create;
		internal static delegate* unmanaged< IntPtr, int, void > CModelMesh_AddVertices;
		internal static delegate* unmanaged< IntPtr, IntPtr, void > CModelMesh_AddFaceGroup;
		internal static delegate* unmanaged< IntPtr, IntPtr, int, void > CModelMesh_SetPositions;
		internal static delegate* unmanaged< IntPtr, IntPtr, int, void > CModelMesh_SetTexCoords;
		internal static delegate* unmanaged< IntPtr, IntPtr, int, void > CModelMesh_SetNormals;
		internal static delegate* unmanaged< IntPtr, int, IntPtr, int, void > CModelMesh_AddFace;
	}
}

internal unsafe static partial class g_pModelDocUtils
{
	[MethodImpl( MethodImplOptions.AggressiveInlining )]
	internal static bool InitFromMesh( global::CModelDoc pModelDoc, string pFilename ) { if ( __N.g_pModelDocUtils_InitFromMesh == null ) throw new System.Exception( "Function Pointer Is Null" );var _str_pFilename = new Sandbox.Interop.InteropString( pFilename ); try { return __N.g_pModelDocUtils_InitFromMesh( pModelDoc, _str_pFilename.Pointer ) != 0; } finally { _str_pFilename.Free(); }  }
	internal static class __N
	{
		internal static delegate* unmanaged< IntPtr, IntPtr, int > g_pModelDocUtils_InitFromMesh;
	}
}

namespace NativeEngine
{
	internal unsafe static partial class ModelDoc
	{
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal static bool CreateModelFromMeshFile( string pVmdlFileFullPath, string meshRelativePath, string material ) { if ( __N.NativeEngine_ModelDoc_CreateModelFromMeshFile == null ) throw new System.Exception( "Function Pointer Is Null" );var _str_material = new Sandbox.Interop.InteropString( material ); try { var _str_meshRelativePath = new Sandbox.Interop.InteropString( meshRelativePath ); try { var _str_pVmdlFileFullPath = new Sandbox.Interop.InteropString( pVmdlFileFullPath ); try { return __N.NativeEngine_ModelDoc_CreateModelFromMeshFile( _str_pVmdlFileFullPath.Pointer, _str_meshRelativePath.Pointer, _str_material.Pointer ) != 0; } finally { _str_pVmdlFileFullPath.Free(); }  } finally { _str_meshRelativePath.Free(); }  } finally { _str_material.Free(); }  }
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal static bool CreateModelFromMesh( string pVmdlFileFullPath, global::CModelMesh pMesh ) { if ( __N.NativeEngine_ModelDoc_CreateModelFromMesh == null ) throw new System.Exception( "Function Pointer Is Null" );var _str_pVmdlFileFullPath = new Sandbox.Interop.InteropString( pVmdlFileFullPath ); try { return __N.NativeEngine_ModelDoc_CreateModelFromMesh( _str_pVmdlFileFullPath.Pointer, pMesh ) != 0; } finally { _str_pVmdlFileFullPath.Free(); }  }
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal static bool CreateModelFromMeshes( string pVmdlFileFullPath, IntPtr pMeshes, int nMeshCount ) { if ( __N.NativeEngine_ModelDoc_CreateModelFromMeshes == null ) throw new System.Exception( "Function Pointer Is Null" );var _str_pVmdlFileFullPath = new Sandbox.Interop.InteropString( pVmdlFileFullPath ); try { return __N.NativeEngine_ModelDoc_CreateModelFromMeshes( _str_pVmdlFileFullPath.Pointer, pMeshes, nMeshCount ) != 0; } finally { _str_pVmdlFileFullPath.Free(); }  }
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal static bool CreateModelFromMeshesWithCollision( string pVmdlFileFullPath, IntPtr pMeshes, IntPtr pCollisionTypes, int nMeshCount ) { if ( __N.NativeEngine_ModelDoc_CreateModelFromMeshesWithCollision == null ) throw new System.Exception( "Function Pointer Is Null" );var _str_pVmdlFileFullPath = new Sandbox.Interop.InteropString( pVmdlFileFullPath ); try { return __N.NativeEngine_ModelDoc_CreateModelFromMeshesWithCollision( _str_pVmdlFileFullPath.Pointer, pMeshes, pCollisionTypes, nMeshCount ) != 0; } finally { _str_pVmdlFileFullPath.Free(); }  }
		internal static class __N
		{
			internal static delegate* unmanaged< IntPtr, IntPtr, IntPtr, int > NativeEngine_ModelDoc_CreateModelFromMeshFile;
			internal static delegate* unmanaged< IntPtr, IntPtr, int > NativeEngine_ModelDoc_CreateModelFromMesh;
			internal static delegate* unmanaged< IntPtr, IntPtr, int, int > NativeEngine_ModelDoc_CreateModelFromMeshes;
			internal static delegate* unmanaged< IntPtr, IntPtr, IntPtr, int, int > NativeEngine_ModelDoc_CreateModelFromMeshesWithCollision;
		}
	}
}

namespace Managed.SourceModelDoc
{
	internal static unsafe class Exports
	{
		/// <summary>
		/// Editor.ModelEditor.ModelDoc.Init( ... )
		/// </summary>
		[UnmanagedCallersOnly]
		internal static void dtrMdldtr_ModelDoc_Init( IntPtr app )
		{
			try
			{
				Editor.ModelEditor.ModelDoc.Init( app );
			}
			catch ( System.Exception ___e )
			{
				Sandbox.Interop.BindingException( "Editor.ModelEditor.ModelDoc", "Init", ___e );
			}
		}
		
		/// <summary>
		/// Editor.ModelEditor.ModelDoc.OnToolsMenu( ... )
		/// </summary>
		[UnmanagedCallersOnly]
		internal static void dtrMdldtr_ModelDoc_OnToolsMenu( IntPtr menu )
		{
			try
			{
				Editor.ModelEditor.ModelDoc.OnToolsMenu( menu );
			}
			catch ( System.Exception ___e )
			{
				Sandbox.Interop.BindingException( "Editor.ModelEditor.ModelDoc", "OnToolsMenu", ___e );
			}
		}
		
	}
	
	internal unsafe static partial class NativeInterop
	{
		static IntPtr _nativeLibraryHandle;
		static bool _initialized;
		
		[UnmanagedFunctionPointer( CallingConvention.Cdecl )]
		internal delegate void _ErrorFunction( string message );
		
		[UnmanagedFunctionPointer( CallingConvention.Cdecl )]
		delegate void NetCoreImportDelegate( int hash, void* imports, void* exports, int* structSizes );
		
		internal static void Initialize()
		{
			if ( _initialized ) return;
			
			string libName = OperatingSystem.IsWindows() ? "tools/modeldoc_editor.dll" : OperatingSystem.IsMacOS() ? "tools/libmodeldoc_editor.dylib" : "tools/libmodeldoc_editor.so";
			if ( !NativeLibrary.TryLoad( System.IO.Path.Combine( NetCore.NativeDllPath, libName ), out var nativeDll ) )
				Sandbox.Interop.NativeAssemblyLoadFailed( libName );
			_nativeLibraryHandle = nativeDll;

			IntPtr nativeInitPtr = NativeLibrary.GetExport( nativeDll, "igen_modeldoc" );
			if ( nativeInitPtr == IntPtr.Zero ) throw new System.Exception( $"Couldn't load from {libName}" );

			var nativeInit = Marshal.GetDelegateForFunctionPointer<NetCoreImportDelegate>( nativeInitPtr );
			if ( nativeInit == null ) throw new System.Exception( $"Couldn't load from {libName}" );
			
			var managedFunctions = new IntPtr[2]
			
			{
				(IntPtr) (delegate* unmanaged<IntPtr, void>) &Exports.dtrMdldtr_ModelDoc_Init,
				(IntPtr) (delegate* unmanaged<IntPtr, void>) &Exports.dtrMdldtr_ModelDoc_OnToolsMenu,
			};
			
			var nativeFunctions = new IntPtr[19];
			
			var structSizes = new int[]
			
			{
			};
			
			
			fixed ( void* m = managedFunctions )
			fixed ( void* n = nativeFunctions )
			fixed ( int* s = structSizes )
			
			{
				nativeInit( 47979, m, n, s );
			}
			
			var onError = Marshal.GetDelegateForFunctionPointer<_ErrorFunction>( nativeFunctions[0] );
			
			try
			{
				CModelDoc.__N.CModelDoc_DeleteThis = (delegate* unmanaged< IntPtr, void >) nativeFunctions[1];
				CModelDoc.__N.CModelDoc_Create = (delegate* unmanaged< IntPtr >) nativeFunctions[2];
				CModelDoc.__N.CModelDoc_SaveToFile = (delegate* unmanaged< IntPtr, IntPtr, int >) nativeFunctions[3];
				NativeModelDoc.CModelDocEditorApp.__N.CMdlDcdtrpp_RefreshGameData = (delegate* unmanaged< IntPtr, void >) nativeFunctions[4];
				NativeModelDoc.CModelDocEditorApp.__N.CMdlDcdtrpp_GetSessionModel = (delegate* unmanaged< IntPtr, IntPtr >) nativeFunctions[5];
				CModelMesh.__N.CModelMesh_DeleteThis = (delegate* unmanaged< IntPtr, void >) nativeFunctions[6];
				CModelMesh.__N.CModelMesh_Create = (delegate* unmanaged< IntPtr >) nativeFunctions[7];
				CModelMesh.__N.CModelMesh_AddVertices = (delegate* unmanaged< IntPtr, int, void >) nativeFunctions[8];
				CModelMesh.__N.CModelMesh_AddFaceGroup = (delegate* unmanaged< IntPtr, IntPtr, void >) nativeFunctions[9];
				CModelMesh.__N.CModelMesh_SetPositions = (delegate* unmanaged< IntPtr, IntPtr, int, void >) nativeFunctions[10];
				CModelMesh.__N.CModelMesh_SetTexCoords = (delegate* unmanaged< IntPtr, IntPtr, int, void >) nativeFunctions[11];
				CModelMesh.__N.CModelMesh_SetNormals = (delegate* unmanaged< IntPtr, IntPtr, int, void >) nativeFunctions[12];
				CModelMesh.__N.CModelMesh_AddFace = (delegate* unmanaged< IntPtr, int, IntPtr, int, void >) nativeFunctions[13];
				g_pModelDocUtils.__N.g_pModelDocUtils_InitFromMesh = (delegate* unmanaged< IntPtr, IntPtr, int >) nativeFunctions[14];
				NativeEngine.ModelDoc.__N.NativeEngine_ModelDoc_CreateModelFromMeshFile = (delegate* unmanaged< IntPtr, IntPtr, IntPtr, int >) nativeFunctions[15];
				NativeEngine.ModelDoc.__N.NativeEngine_ModelDoc_CreateModelFromMesh = (delegate* unmanaged< IntPtr, IntPtr, int >) nativeFunctions[16];
				NativeEngine.ModelDoc.__N.NativeEngine_ModelDoc_CreateModelFromMeshes = (delegate* unmanaged< IntPtr, IntPtr, int, int >) nativeFunctions[17];
				NativeEngine.ModelDoc.__N.NativeEngine_ModelDoc_CreateModelFromMeshesWithCollision = (delegate* unmanaged< IntPtr, IntPtr, IntPtr, int, int >) nativeFunctions[18];
			}
			catch ( System.Exception ___e )
			{
				onError( $"{___e.Message}\n\n{___e.StackTrace}" );
			}
			_initialized = true;
		}
		internal static void Free()
		{
			if ( _nativeLibraryHandle == IntPtr.Zero ) return;
			NativeLibrary.Free( _nativeLibraryHandle );
			_nativeLibraryHandle = IntPtr.Zero;
			_initialized = false;
		}
	}
}
