// <auto-generated>
// This file was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

internal static class SandboxToolsInteropAnimgraphInternal
{
	public static int Convert( Type t )
	{
		if ( typeof( global::Editor.BaseScrollWidget ).IsAssignableFrom( t ) ) return 256245278;
		if ( typeof( global::Editor.Button ).IsAssignableFrom( t ) ) return 2120449044;
		if ( typeof( global::Editor.Checkbox ).IsAssignableFrom( t ) ) return 772888385;
		if ( typeof( global::Editor.ComboBox ).IsAssignableFrom( t ) ) return 256233403;
		if ( typeof( global::Editor.Frame ).IsAssignableFrom( t ) ) return 416267623;
		if ( typeof( global::Editor.GraphicsView ).IsAssignableFrom( t ) ) return 774054386;
		if ( typeof( global::Editor.Label ).IsAssignableFrom( t ) ) return -1333028724;
		if ( typeof( global::Editor.LineEdit ).IsAssignableFrom( t ) ) return -2137430376;
		if ( typeof( global::Editor.MenuBar ).IsAssignableFrom( t ) ) return -1325607872;
		if ( typeof( global::Editor.StatusBar ).IsAssignableFrom( t ) ) return -1890426169;
		if ( typeof( global::Editor.TextEdit ).IsAssignableFrom( t ) ) return 1008106499;
		if ( typeof( global::Editor.ToolBar ).IsAssignableFrom( t ) ) return -2124457813;
		if ( typeof( global::Editor.Window ).IsAssignableFrom( t ) ) return -1571505210;
		if ( typeof( global::Editor.DockManager ).IsAssignableFrom( t ) ) return -2135796158;
		if ( typeof( global::Editor.GraphicsItem ).IsAssignableFrom( t ) ) return 2109064242;
		if ( typeof( global::Editor.GraphicsScene ).IsAssignableFrom( t ) ) return -735098127;
		if ( typeof( global::Editor.GraphicsWidget ).IsAssignableFrom( t ) ) return -120989933;
		if ( typeof( global::Editor.Option ).IsAssignableFrom( t ) ) return 780535505;
		if ( typeof( global::Editor.TrayIcon ).IsAssignableFrom( t ) ) return 1020660495;
		if ( typeof( global::Editor.Widget ).IsAssignableFrom( t ) ) return 323741830;
		
		throw new System.Exception( $"Can't handle type {t}" );
	}
}
namespace NativeAnimgraph
{
	internal unsafe readonly partial struct CQAnimGraphPreviewDockWidget
	{
		internal readonly IntPtr self;
		
		// Allow blindly converting from an IntPtr
		static public implicit operator IntPtr( CQAnimGraphPreviewDockWidget value ) => value.self;
		static public implicit operator CQAnimGraphPreviewDockWidget( IntPtr value ) => new CQAnimGraphPreviewDockWidget( value );
		
		// Allow us to compare these pointers
		public static bool operator ==( CQAnimGraphPreviewDockWidget c1, CQAnimGraphPreviewDockWidget c2 ) => c1.self == c2.self;
		public static bool operator !=( CQAnimGraphPreviewDockWidget c1, CQAnimGraphPreviewDockWidget c2 ) => c1.self != c2.self;
		public readonly override bool Equals( object obj ) => obj is CQAnimGraphPreviewDockWidget c && c == this;
		
		internal CQAnimGraphPreviewDockWidget( IntPtr ptr ) { self = ptr; }
		public override string ToString() => $"CQAnimGraphPreviewDockWidget {self:x}";
		// Helpers to check validity
		
		internal readonly bool IsNull{ [MethodImpl( MethodImplOptions.AggressiveInlining )] get { return self == IntPtr.Zero; } }
		internal readonly bool IsValid => !IsNull;
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal readonly IntPtr GetPointerAssertIfNull(){ if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CQAnimGraphPreviewDockWidget was null" ); return self; }
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		public readonly override int GetHashCode() => self.GetHashCode();
		
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal readonly string GetPreviewModel() { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CQAnimGraphPreviewDockWidget was null when calling GetPreviewModel" );return Sandbox.Interop.GetString( __N.CQnmGrphPrvwDckW_GetPreviewModel( self ) ); }
		[MethodImpl( MethodImplOptions.AggressiveInlining )]
		internal readonly void SetPreviewModel( string model ) { if ( self == IntPtr.Zero ) throw new System.NullReferenceException( "CQAnimGraphPreviewDockWidget was null when calling SetPreviewModel" );var _str_model = new Sandbox.Interop.InteropString( model ); try { __N.CQnmGrphPrvwDckW_SetPreviewModel( self, _str_model.Pointer ); } finally { _str_model.Free(); }  }
		internal static class __N
		{
			internal static delegate* unmanaged< IntPtr, IntPtr > CQnmGrphPrvwDckW_GetPreviewModel;
			internal static delegate* unmanaged< IntPtr, IntPtr, void > CQnmGrphPrvwDckW_SetPreviewModel;
		}
	}
}

namespace Managed.SourceAnimgraph
{
	internal static unsafe class Exports
	{
		/// <summary>
		/// Editor.Animgraph.CreateModelPicker( ... )
		/// </summary>
		[UnmanagedCallersOnly]
		internal static IntPtr Editor_Animgraph_CreateModelPicker( IntPtr widget )
		{
			try
			{
				return Editor.Animgraph.CreateModelPicker( widget );
			}
			catch ( System.Exception ___e )
			{
				Sandbox.Interop.BindingException( "Editor.Animgraph", "CreateModelPicker", ___e );
				return default;
			}
		}
		
	}
	
	internal unsafe static partial class NativeInterop
	{
		static IntPtr _nativeLibraryHandle;
		static bool _initialized;
		
		[UnmanagedFunctionPointer( CallingConvention.Cdecl )]
		internal delegate void _ErrorFunction( string message );
		
		[UnmanagedFunctionPointer( CallingConvention.Cdecl )]
		delegate void NetCoreImportDelegate( int hash, void* imports, void* exports, int* structSizes );
		
		internal static void Initialize()
		{
			if ( _initialized ) return;
			
			string libName = OperatingSystem.IsWindows() ? "tools/animgraph_editor.dll" : OperatingSystem.IsMacOS() ? "tools/libanimgraph_editor.dylib" : "tools/libanimgraph_editor.so";
			if ( !NativeLibrary.TryLoad( System.IO.Path.Combine( NetCore.NativeDllPath, libName ), out var nativeDll ) )
				Sandbox.Interop.NativeAssemblyLoadFailed( libName );
			_nativeLibraryHandle = nativeDll;

			IntPtr nativeInitPtr = NativeLibrary.GetExport( nativeDll, "igen_animgraph" );
			if ( nativeInitPtr == IntPtr.Zero ) throw new System.Exception( $"Couldn't load from {libName}" );

			var nativeInit = Marshal.GetDelegateForFunctionPointer<NetCoreImportDelegate>( nativeInitPtr );
			if ( nativeInit == null ) throw new System.Exception( $"Couldn't load from {libName}" );
			
			var managedFunctions = new IntPtr[1]
			
			{
				(IntPtr) (delegate* unmanaged<IntPtr, IntPtr>) &Exports.Editor_Animgraph_CreateModelPicker,
			};
			
			var nativeFunctions = new IntPtr[3];
			
			var structSizes = new int[]
			
			{
			};
			
			
			fixed ( void* m = managedFunctions )
			fixed ( void* n = nativeFunctions )
			fixed ( int* s = structSizes )
			
			{
				nativeInit( 30831, m, n, s );
			}
			
			var onError = Marshal.GetDelegateForFunctionPointer<_ErrorFunction>( nativeFunctions[0] );
			
			try
			{
				NativeAnimgraph.CQAnimGraphPreviewDockWidget.__N.CQnmGrphPrvwDckW_GetPreviewModel = (delegate* unmanaged< IntPtr, IntPtr >) nativeFunctions[1];
				NativeAnimgraph.CQAnimGraphPreviewDockWidget.__N.CQnmGrphPrvwDckW_SetPreviewModel = (delegate* unmanaged< IntPtr, IntPtr, void >) nativeFunctions[2];
			}
			catch ( System.Exception ___e )
			{
				onError( $"{___e.Message}\n\n{___e.StackTrace}" );
			}
			_initialized = true;
		}
		internal static void Free()
		{
			if ( _nativeLibraryHandle == IntPtr.Zero ) return;
			NativeLibrary.Free( _nativeLibraryHandle );
			_nativeLibraryHandle = IntPtr.Zero;
			_initialized = false;
		}
	}
}
