#!/usr/bin/env node
import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";
import { runAgent } from "./agent.js";
import { buildRbxlx } from "./rbxlx.js";

function getPrompt(): string {
  const args = process.argv.slice(2);
  const promptArg = args.find((a) => !a.startsWith("--"));
  if (!promptArg) {
    console.error(
      "Usage: roblox-map-agent \"<map theme prompt>\"\n\n" +
        "Example:\n" +
        "  roblox-map-agent \"a small medieval village by a river, with a tavern, market square, and watchtower\""
    );
    process.exit(1);
  }
  return promptArg;
}

function getEnv(name: string): string {
  const v = process.env[name];
  if (!v) {
    console.error(`Missing required env var: ${name}. Copy .env.example to .env and fill it in.`);
    process.exit(1);
  }
  return v;
}

async function main() {
  const prompt = getPrompt();
  const anthropicApiKey = getEnv("ANTHROPIC_API_KEY");
  const geminiApiKey = getEnv("GOOGLE_API_KEY");

  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const outputRoot = path.resolve("output", stamp);
  const imageDir = path.join(outputRoot, "generated-assets");
  await fs.mkdir(imageDir, { recursive: true });

  console.log(`\nBuilding map for: "${prompt}"`);
  console.log(`Output folder: ${outputRoot}\n`);

  const state = await runAgent({
    initialPrompt: prompt,
    anthropicApiKey,
    geminiApiKey,
    imageDir,
  });

  const rbxlx = buildRbxlx(state.toSpec());
  const rbxlxPath = path.join(outputRoot, "map.rbxlx");
  await fs.writeFile(rbxlxPath, rbxlx, "utf8");

  const summary = [
    `# Roblox Map: ${prompt}`,
    ``,
    `Generated by roblox-map-agent on ${new Date().toISOString()}.`,
    ``,
    `## Files`,
    `- \`map.rbxlx\` — drag this into Roblox Studio (File > Open, or just drag onto the Studio window).`,
    `- \`generated-assets/\` — ${state.images.length} PNG(s) Gemini produced for skybox + decals.`,
    ``,
    `## Stats`,
    `- Loose parts: ${state.parts.length}`,
    `- Models: ${state.models.length}`,
    `- Generated images: ${state.images.length}`,
    `- Skybox set: ${state.skybox ? "yes" : "no"}`,
    ``,
    `## Importing the images into Studio`,
    `Decals and skybox faces in the .rbxlx reference \`rbxasset://localfile/<name>.png\` placeholders. To make them appear in-game:`,
    ``,
    `1. Open Roblox Studio with \`map.rbxlx\`.`,
    `2. In Studio, go to **View > Asset Manager**, then upload each PNG from \`generated-assets/\` (Studio gives you an \`rbxassetid://\` URL after upload).`,
    `3. Select the Decal/Sky in the Explorer and replace the \`Texture\` (or \`SkyboxUp\`/etc.) URL with the new \`rbxassetid://\` value.`,
    ``,
    `If you skip step 2-3, the geometry and materials still render fine; only the generated art will show as missing.`,
    ``,
    `## Generated images`,
    ...state.images.map((i) => `- **${i.id}** (\`${path.basename(i.filepath)}\`): ${i.prompt}`),
  ].join("\n");

  await fs.writeFile(path.join(outputRoot, "README.md"), summary, "utf8");

  console.log(`\nDone.`);
  console.log(`  ${rbxlxPath}`);
  console.log(`  ${path.join(outputRoot, "README.md")}`);
}

main().catch((err) => {
  console.error("\nAgent failed:", err);
  process.exit(1);
});
